// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4sOw-9Qualkic13Kr894ryKg4IOty-mE',
    appId: '1:674144733932:web:549914cac246d9619333c9',
    messagingSenderId: '674144733932',
    projectId: 'carlet-68fca',
    authDomain: 'carlet-68fca.firebaseapp.com',
    storageBucket: 'carlet-68fca.firebasestorage.app',
    measurementId: 'G-16PSWM32SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyDoNNfY5fJX1Ok1FXSgS7RoOVDvAg80Q',
    appId: '1:674144733932:android:16dc51d0569eb0799333c9',
    messagingSenderId: '674144733932',
    projectId: 'carlet-68fca',
    storageBucket: 'carlet-68fca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3z6ouiXbxtjKwCbfZZC4sxLOx8olAM_M',
    appId: '1:674144733932:ios:1b91b6ab957aa28f9333c9',
    messagingSenderId: '674144733932',
    projectId: 'carlet-68fca',
    storageBucket: 'carlet-68fca.firebasestorage.app',
    iosBundleId: 'com.techolosh.carlet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3z6ouiXbxtjKwCbfZZC4sxLOx8olAM_M',
    appId: '1:674144733932:ios:e2d071a5ca5909399333c9',
    messagingSenderId: '674144733932',
    projectId: 'carlet-68fca',
    storageBucket: 'carlet-68fca.firebasestorage.app',
    iosBundleId: 'com.example.carlet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4sOw-9Qualkic13Kr894ryKg4IOty-mE',
    appId: '1:674144733932:web:f0bf32b4f57be2159333c9',
    messagingSenderId: '674144733932',
    projectId: 'carlet-68fca',
    authDomain: 'carlet-68fca.firebaseapp.com',
    storageBucket: 'carlet-68fca.firebasestorage.app',
    measurementId: 'G-TYCVXS0EKL',
  );
}
